name: Build and publish package to TestPyPI

on:
  push:
    branches:
      - release-candidate

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build_and_publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout to release-candidate
        uses: actions/checkout@v4
        with:
          ref: release-candidate
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]
      - name: Build
        run: package --build-number
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          repository-url: https://test.pypi.org/legacy/
